import iniciaScrollSuave from './modules/scroll-suave.js';
import iniciaAnimacaoScroll from './modules/scroll-animacao.js';
import navegacaoTab from './modules/navegacao-tab.js';
import iniciaAccordion from './modules/accordion.js';
import iniciaModal from './modules/modal.js';
import iniciaTooltip from './modules/tooltip.js';
import iniciaMenuDropdown from './modules/menu-dropdown.js';
import iniciaMenuMobile from './modules/menu-mobile.js';
import iniciaAnimacaoNumeros from './modules/anima-numeros.js';
import iniciaFuncionamento from './modules/horario-funcionamento.js';

iniciaScrollSuave();
iniciaAnimacaoScroll();
navegacaoTab();
iniciaAccordion();
iniciaModal();
iniciaTooltip();
iniciaMenuDropdown();
iniciaMenuMobile();
iniciaAnimacaoNumeros();
iniciaFuncionamento();